kind: pipeline
type: kubernetes
name: juju-test

metadata:
  namespace: drone

steps:
- name: juju
  image: jujusolutions/jujubox:latest
  environment:
    DRONECI_PASSWD:
      from_secret: juju-droneci-passwd
  commands:
  - echo $${DRONECI_PASSWD} | juju login juju.lab-linux.com -u droneci
  - juju deploy postgresql -m drone-minecraft-demo
  - juju deploy ./charms/minetest-server --series bionic -m drone-minecraft-demo
  - juju add-relation postgresql:db minetest-server:db -m drone-minecraft-demo