options:
  port:
      default: 30000
      description: Server port to listen on
      type: int
  server-name:
      default: "Minetest server"
      description: Name of the server
      type: string
  server-description:
      default: "Juju deployed Minetest server"
      description: Description of server
      type: string
  motd:
      default: "Welcome!"
      description: Message of the day
      type: string
  strict-protocol-version-checking:
      default: "false"
      description: Set to true to disallow old clients from connecting
      type: string
  creative-mode:
      default: "false"
      description: Set to true to enable creative mode (unlimited inventory)
      type: string
  enable-damage:
      default: "false"
      description: Enable players getting damage and dying
      type: string
  default-password:
      default: ""
      description: New users need to input this password
      type: string
  default-privs:
      default: "build,shout"
      description: |
          Available privileges: build, shout, teleport, settime, privs, ban
          See /privs in game for a full list on your server and mod configuration
      type: string
  enable-pvp:
      default: "true"
      description: Whether to enable players killing each other
      type: string